cinema/Controllers/PublicController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.Extensions.Options;
using WebApplication.Services;
using WebApplication.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Authentication;
using System.Security.Claims;

namespace WebApplication.Controllers
{
    public class PublicController : BaseController
    {
        public PublicController(IOptions<GlobalOption> globalOptions) : base(globalOptions)
        {

        }
        public IActionResult Index()
        {
            ViewBag.SlidSowData = _dbAccess.SpGetMoviesImageURL();
            ViewBag.RunningMovies = _dbAccess.FillMovieList();
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            Session["UserInfo"] = null;
            Session["IsAdmin"] = null;
            Session.Clear();
            await HttpContext.Authentication.SignOutAsync("MyCookieMiddlewareInstance");
            ViewBag.Error = "Logout successfully !";
            return View("Login");
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact([FromForm]VMFeedback formData)
        {
            try
            {
                string mail = "";
                mail += "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title></title></head><body><div style=\"border: 1px solid #993333; width: 450px; height: 350px; background-color: #CCCCCC;\"><table  style=\"width:100%\"><tr><td style=\"width: 58px;\">Name :</td><td>";
                mail += formData.txtContact.Trim().ToUpper();
                mail += "</td></tr><tr><td style=\"width: 58px;\">Address :</td><td>";
                mail += formData.txtAddress.Trim().ToUpper();
                mail += "</td></tr><tr><td style=\"width: 58px;\">Contact :</td><td>";
                mail += formData.txtContact.Trim().ToUpper();
                mail += "</td></tr><tr><td style=\"width: 58px;\">Email :</td><td>";
                mail += formData.txtEmail.Trim().ToUpper();
                mail += "</td></tr><tr><td style=\"width: 58px;\">Views :</td><td>";
                mail += formData.txtViews.Trim().ToUpper();
                mail += "</td></tr></table></div></body></html>";
                try
                {
                    //MailGmail.SendEmail("cinemaol.asct@gmail.com", "CONCERNS/FEEDBACK", mail, "");
                    // MailGmail.SendEmail(obj.txtEmail"].Trim().ToLower(), "CinemaOL", "Thank you for visiting CinemaOl !", "");
                }
                catch (Exception)
                {
                }

                ViewBag.Msg = "Thanx for your feedback.";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Msg = "Error. ## " + ex.Message;
                return View();
            }

        }

        [HttpPost]
        public IActionResult Login([FromForm]VMLogin obj)
        {
            UserInfo dataTable = _dbAccess.SpUserLogin(obj);
            if (dataTable != null)
            {
                LoginInner(dataTable);
                Session["UserInfo"] = dataTable;
                Session["IsAdmin"] = null;
            }
            else
            {
                ViewBag.Error = "Invalid user name or/ and password !";
                return View("Login");
            }
            //System.Web.Security.FormsAuthentication.RedirectFromLoginPage("LoggedUser", false);
            return RedirectToAction("Index");
        }
        public IActionResult LoginAdmin()
        {
            ViewBag.ForAdmin = true;
            return View("Login");
        }

        [HttpPost]
        public IActionResult LoginAdmin([FromForm]VMLogin obj)
        {
            UserInfo dataTable = _dbAccess.SpUserLogin(obj, true);
            if (dataTable != null)
            {
                LoginInner(dataTable,"Admin");
                Session["UserInfo"] = dataTable;
                Session["IsAdmin"] = true;
            }
            else
            {
                ViewBag.Error = "Invalid user name or/ and password !";
                ViewBag.ForAdmin = true;
                return View("Login");
            }
            //System.Web.Security.FormsAuthentication.RedirectFromLoginPage("AdminUser", false);
            return RedirectToAction("Index", "Admin");
        }

        [HttpPost]
        public ActionResult MakeShowSelection([FromForm]VMSelectShowPost obj)
        {
            //return Content(Newtonsoft.Json.JsonConvert.SerializeObject(obj));
            try
            {
                if (Session["UserInfo"] == null)
                {
                    TempData["Msg"] = "You must have to looged in before you book a ticket.";
                    return RedirectToAction("Login");
                }
                else
                {
                    Session["ShowId"] = _dbAccess.GetShowId(obj);
                    return RedirectToAction("SelectSheats", "TicketBooking");
                }
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Error. ## " + ex.Message;
                return RedirectToAction("Login");
            }
        }

        public IActionResult Error()
        {
            var feature = HttpContext.Features.Get<IExceptionHandlerFeature>();
            ViewBag.Error = feature?.Error.InnerException.StackTrace;
            return View();
        }

        public IActionResult Movie()
        {
            return View(_dbAccess.GetRunningMovies());
        }

        public IActionResult MovieUpComming()
        {
            return View(_dbAccess.GetUpCommingMovies());
        }

        public IActionResult Captcha()
        {
            string strString = "ABCDEFGHJKLMNOPQRSTUVWXYZ23456789";
            Random random = new Random();
            int randomCharIndex = 0;

            string captcha = "";
            for (int i = 0; i < 7; i++)
            {
                randomCharIndex = random.Next(0, strString.Length);
                captcha += Convert.ToString(strString[randomCharIndex]);
            }
            Session["CAPTCHA_CODE"] = captcha.Trim().ToUpper();
            return Content(captcha.Trim().ToUpper());
        }

        public IActionResult ResetPass()
        {
            ViewBag.Step = 1;
            return View();
        }

        [HttpPost]
        public IActionResult ResetPass([FromForm]VMPwdReset formData)
        {
            UserInfo dt = null;
            switch (Convert.ToInt32(formData.Step))
            {
                case 1:
                    dt = _dbAccess.SpCheckUser(formData.txtUserName.Trim().ToUpper());
                    if (dt != null)
                    {
                        Session["UserCheck"] = dt;
                        ViewBag.SQ = dt.User_SQ.ToString().ToUpper();
                        ViewBag.Step = 2;
                    }
                    else
                    {
                        ViewBag.Step = 1;
                        ViewBag.Msg = "No user exists with this user name.";
                    }
                    break;
                case 2:
                    dt = Session.Get<UserInfo>("UserCheck");
                    if (dt.User_SA.ToString().ToUpper() == formData.txtSA.Trim().ToUpper())
                    {
                        ViewBag.Step = 3;
                    }
                    else
                    {
                        ViewBag.SQ = dt.User_SQ.ToString().ToUpper();
                        ViewBag.Step = 2;
                        ViewBag.Msg = "Security answer is wrong.";
                    }
                    break;
                case 3:
                    dt = Session.Get<UserInfo>("UserCheck");
                    dt.User_LoginPassword = formData.txtRePass.Trim();
                    if (_dbAccess.SpChangePassword(dt))
                    {
                        ViewBag.Msg = "Password reset successfully.";
                        ViewBag.Step = 1;
                    }
                    else
                    {
                        ViewBag.Step = 3;
                        ViewBag.Msg = "Error .## Oops some problems occured !";
                    }

                    break;
                default:
                    ViewBag.Step = 1;
                    break;
            }
            return View();
        }

        public IActionResult Register()
        {
            var data = _dbAccess.GetAllStates();
            List<SelectListItem> dataList = new List<SelectListItem>();
            dataList.Insert(0, new SelectListItem() { Value = "0", Text = "<-- SELECT STATE -->" });
            foreach (var item in data)
            {
                dataList.Add(new SelectListItem() { Text = item, Value = item });
            }
            return View(dataList);
        }

        [HttpPost]
        public IActionResult Register([FromForm]VMRegister obj)
        {
            try
            {
                if (!_dbAccess.IsUserExists(obj.txtUName))
                {
                    if (Session["CAPTCHA_CODE"].ToString().ToUpper().Equals(obj.txtVeriCode.Trim().ToUpper()))
                    {
                        if (_dbAccess.RegisterUser(obj))
                        {
                            var dt = _dbAccess.SpUserLogin(new VMLogin() { txtLoginId = obj.txtUName, txtLoginPass = obj.txtRePass });
                            Session["UserInfo"] = dt;
                            Session["IsAdmin"] = null;
                            return RedirectToAction("Index");
                        }
                        else
                        {

cinema/Controllers/ServiceController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplication.Services;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ServiceController : BaseController
    {
        public ServiceController(IOptions<GlobalOption> globalOptions) : base(globalOptions)
        {

        }

        [HttpPost]
        public IActionResult FillDateList([FromBody]VMSelectShow obj)
        {
            try
            {
                return Json(_dbAccess.FillDateList(obj.pMovieTitle));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult FillTimeList([FromBody]VMSelectShow obj)
        {
            try
            {
                return Json(_dbAccess.FillTimeList(obj.pMovieTitle, obj.pMovieDate));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

cinema/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplication.Services;
using WebApplication.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace WebApplication.Controllers
{
    public class UserProfileController : BaseController
    {
        public UserProfileController(IOptions<GlobalOption> globalOptions) : base(globalOptions)
        {

        }

        [Authorize]
        public IActionResult UserHome()
        {
            var user_info = Session.Get<UserInfo>("UserInfo");
            return View(user_info);
        }
        [Authorize]
        public IActionResult EditProfile()
        {
            List<SelectListItem> dataList = new List<SelectListItem>();
            dataList.Insert(0, new SelectListItem() { Value = "0", Text = "<-- SELECT STATE -->" });
            foreach (var item in _dbAccess.GetAllStates())
            {
                dataList.Add(new SelectListItem() { Text = Convert.ToString(item), Value = Convert.ToString(item) });
            }
            ViewBag.States = dataList;
            var user_info = Session.Get<UserInfo>("UserInfo");
            return View(user_info);
        }

        [Authorize]
        [HttpPost]
        public IActionResult EditProfile([FromForm]UserInfo obj)
        {
            try
            {
                if (Session["UserInfo"] != null)
                {
                    var user_info = Session.Get<UserInfo>("UserInfo");
                    obj.User_LoginName = user_info.User_LoginName;
                    obj.User_LoginPassword = user_info.User_LoginPassword;
                    if (_dbAccess.SpUpdateUserInfo(obj))
                    {
                        UserInfo dataTable = _dbAccess.SpUserLogin(new VMLogin() { txtLoginId = obj.User_LoginName, txtLoginPass = obj.User_LoginPassword });
                        if (dataTable != null)
                        {
                            Session["UserInfo"] = dataTable;
                            Session["IsAdmin"] = null;
                        }
                        TempData["Msg"] = "Updated successfully.";
                        return RedirectToAction("EditProfile");
                    }
                    else
                    {
                        throw new Exception("Oops some error occured !");
                    }
                }
                else
                {
                    throw new Exception("No user is logged in !");
                }
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Error. ## " + ex.Message;
                return RedirectToAction("EditProfile");
            }
        }

        [Authorize]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult ChangePassword([FromForm]VMPwdReset obj)
        {
            try
            {
                if (Session["UserInfo"] != null)
                {
                    var user_info = Session.Get<UserInfo>("UserInfo");
                    if (user_info.User_LoginPassword.ToString() == obj.txtCurrentPass.Trim())
                    {
                        user_info.User_LoginPassword = obj.txtNewRePass.Trim();
                        if (_dbAccess.SpChangePassword(user_info))
                        {
                            TempData["Msg"] = "Password Changed Successfully.";
                            return RedirectToAction("ChangePassword");
                        }
                        else
                        {
                            throw new Exception("Oops some problems occured !");
                        }
                    }
                    else
                    {
                        throw new Exception("Current password is not correct !");
                    }
                }
                else
                {
                    throw new Exception("No user is logged in !");
                }

            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Error. ## " + ex.Message;
                return RedirectToAction("ChangePassword");
            }
        }

        [Authorize]
        public IActionResult BookingHistory([FromForm]BookingHistory obj)
        {
            return BookingHistoryInner(obj);
        }
   [Authorize]
        public IActionResult BookingHistoryAjax([FromQuery]BookingHistory obj)
        {
            return BookingHistoryInner(obj);
        }

        private IActionResult BookingHistoryInner(BookingHistory obj)
        {
            if (obj == null)
            {
                obj = new BookingHistory();
            }
            var user_info = Session.Get<UserInfo>("UserInfo");
            obj.page = (obj.page ?? 1);
            var data = _dbAccess.SpBookingHistoryWithPaging(user_info.User_Id, 10, obj.page.Value);
            ViewBag.RecordsCount = data.LastOrDefault().RecordCount;
            ViewBag.PageNo = (obj.page ?? 1);
            if (obj.forAjax == null)
            {
                return View(data.Take(data.Count - 1).ToList());
            }
            else
            {
                return PartialView("_MovieHistory", data.Take(data.Count - 1).ToList());
            }
        }

        [Authorize]
        public IActionResult BookingDetail(Int32 id)
        {
            var data = _dbAccess.SpGetTicketHistoryDetial(id);
            return View(data);
        }
    }
}

cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>CinemaOL | An Online Cinema Ticket Booking System</title>
    <script type="text/javascript">
        window.history.forward(1);
    </script>
    <script type="text/javascript" src="@Url.Content("~/resources/jquery-1.6.1.min.js")"></script>
    <script type="text/javascript">
        var rev = "fwd";
        function titlebar(val) {
            var msg = "CinemaOL | An Online Cinema Ticket Booking System";
            var res = " ";
            var speed = 100;
            var pos = val;

            msg = "" + msg + "";
            var le = msg.length;
            if (rev == "fwd") {
                if (pos < le) {
                    pos = pos + 1;
                    scroll = msg.substr(0, pos);
                    document.title = scroll;
                    timer = window.setTimeout("titlebar(" + pos + ")", speed);
                }
                else {
                    rev = "bwd";
                    timer = window.setTimeout("titlebar(" + pos + ")", speed);
                }
            }
            else {
                if (pos > 0) {
                    pos = pos - 1;
                    var ale = le - pos;
                    scrol = msg.substr(ale, le);
                    document.title = scrol;
                    timer = window.setTimeout("titlebar(" + pos + ")", speed);
                }
                else {
                    rev = "fwd";
                    timer = window.setTimeout("titlebar(" + pos + ")", speed);
                }
            }
        }

        titlebar(0);
    </script>
    @RenderSection("head", false)
    <link href="@Url.Content("~/resources/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/favicon.ico")" rel="Shortcut Icon" />
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div style="width: 300px; height: 100px; float: left;">
                <a href="@Url.Action("Index", "Public")">
                    <img src="@Url.Content("~/images/appImages/logo.png")"  height="100px" width="300px" alt="CinemaOL" id="logo" />
                </a>
            </div>
            
            @Html.Partial("_LoginView")

        </div>
    </div>
    <div id="content">
        @RenderBody()
    </div>

    <div id="footer">
        <div style="height: 20px;">
            <div style="width: 600px; float: left">
                <ul style="padding: 0px; margin: 0px; list-style-type: none; height: 20px; width: 600px;">
                    <li style="float: left;">Designed and Developed by Mata Prasad Chauhan.
        All Rights Reserved &copy; 2012
                    </li>
                </ul>
            </div>
            <div style="width: 100px; height: 20px; float: right;">


                <ul style="padding: 0px; width: 100px; height: 20px; float: right; margin: 0px; list-style-type: none;">
                    <li style="float: right; height: 20px; width: 100px; margin: 0px; padding: 0px;">
                        <a href="@Url.Action("LoginAdmin", "Public")"
                                style="width: 100px; height: 20px; display: block; line-height: 20px; vertical-align: middle; text-align: center; color: #808000; text-decoration: underline; font-weight: bold; font-size: 12pt;">Admin Login  </a></li>
                </ul>

            </div>
        </div>
    </div>
</body>
</html>

cinema/Views/Shared/_LoginView.cshtml
@using Microsoft.AspNetCore.Http;
@using WebApplication.Services;
@using WebApplication.Models;
@using System.Security.Claims;
<div style="width: 500px; height: 100px; float: right;">
    <div id="LoginRegister" runat="server" class="menu_" style="height: 50%; display: block; vertical-align: top; text-align: right; line-height: 100%;">
        @{
            if (Context.Session.GetItem("UserInfo") != null)
            {
                UserInfo dt = Context.Session.GetItem<UserInfo>("UserInfo");
                string name = dt.User_FName + " " + dt.User_LName;
                if (name.Length > 20)
                {
                    name = name.Substring(0, 20).ToUpper();
                }
            <a href="@Url.Action("LogOut", "Public")">Log Out</a> <a class="xx" style=" width:300px;background-color: #ffffff; " href="@Url.Action("UserHome", "UserProfile")" title="Click to go your Account Home !">Welcome  @name</a>
            }
            else
            {
            <a href="@Url.Action("Login", "Public")">Login</a> <a href="@Url.Action("Register", "Public")">Register</a>
            }
        }

    </div>
    <div class="menu_" style="height: 50%; display: block; vertical-align: top; text-align: right; line-height: 100%;">
        @{if (Context.Session.GetItem("IsAdmin") == null)
          {
            <a href="@Url.Action("Contact", "Public")" >ContactUs</a><a href="@Url.Action("About", "Public")">AboutUs</a><a
                            href="@Url.Action("Movie", "Public")">Movies</a><a
                                href="@Url.Action("Index", "Public")">Home</a>
          }
          else
          {
            <a href="@Url.Action("AddMovie","Admin")" style="width: 150px;">AddMovies</a>
            <a href="@Url.Action("RemoveMovie","Admin")" style="width: 150px;">RemoveMovies</a>
            <a href="@Url.Action("ManageShow","Admin")" style="width: 150px;">ManageShows</a>
          }
        }
        <br />
        <br />
        <center>
                        Your IP is: @Context.Connection.RemoteIpAddress
                    </center>
    </div>
</div>

cinema/Views/Shared/_MovieDetail.cshtml
@using WebApplication.Models;
@model MovieInfo
<h3><a href="#">@Model.Movie_Title</a></h3>
<div>
    <div style="padding: 5px; margin: 0px auto 0px auto; width: 100%;">

        <div style="padding: 0px; margin: 5px auto 5px auto; border: 1px solid #000000; width: 600px; height: 300px;">
            <img src="@Url.Content("~/" + @Model.Movie_ImageURL)" style=" height:300px; width:600px;" alt="" />
        </div>
        <div style="padding: 0px; margin: 0px auto 0px auto; width: 100%; height: 218px;">
            <div style="height: 20px;">
            </div>
            <table border="1" class="style1">
                <tr>
                    <td class="style2">
                        <span style="height: 30px; display: block; line-height: 30px; vertical-align: middle; text-align: left; color: #000000; font-weight: bold; font-size: 15pt; padding: 0px 0px 0px 10px; margin: 0px">DIRECTOR : </span>
                    </td>
                    <td align="left">
                        @Model.Movie_Director
                    </td>
                </tr>
                <tr>
                    <td class="style2"
                        style="border-color: black; border-style: none; border-width: 1px;">
                        <span style="height: 30px; display: block; line-height: 30px; vertical-align: middle; text-align: left; color: #000000; font-weight: bold; font-size: 15pt; padding: 0px 0px 0px 10px; margin: 0px">CASTS : </span>
                    </td>
                    <td rowspan="4">
                        <div align="left" style="height: 85px">
                            @Model.Movie_Casts
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="style2"
                        style="border-color: black; border-style: none; border-width: 1px;">&nbsp;</td>
                </tr>
                <tr>
                    <td class="style2"
                        style="border-color: black; border-style: none; border-width: 1px;">&nbsp;</td>
                </tr>
                <tr>
                    <td class="style2"
                        style="border-color: black; border-style: none; border-width: 1px;">&nbsp;</td>
                </tr>
                <tr>
                    <td class="style2">
                        <span style="height: 30px; display: block; line-height: 30px; vertical-align: middle; text-align: left; color: #000000; font-weight: bold; font-size: 15pt; padding: 0px 0px 0px 10px; margin: 0px">RELEASE DATE : </span>
                    </td>
                    <td align="left">
                        @Model.Movie_ReleaseDate
                    </td>
                </tr>
                <tr>
                    <td class="style2">
                        <span style="height: 30px; display: block; line-height: 30px; vertical-align: middle; text-align: left; color: #000000; font-weight: bold; font-size: 15pt; padding: 0px 0px 0px 10px; margin: 0px">LANGUAGE : </span>
                    </td>
                    <td align="left">
                        @Model.Movie_Language
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

cinema/Views/Shared/_MovieHistory.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc.Rendering;
@using WebApplication.Services;
@using WebApplication.Models;
@model List<BookingHistory>
<table cellspacing="0" cellpadding="3" rules="all" border="1" style="width: 100%; background-color: White; border-color: #000000; border-width: 1px; border-style: solid; font-size: Small; border-collapse: collapse;">
    <tr style="color: White; background-color: #006699; font-weight: bold;">
        <th scope="col">Booking Date</th>
        <th scope="col">Show Date</th>
        <th scope="col">Show Time</th>
        <th scope="col">Movie Name</th>
        <th scope="col">OL Ticket Number</th>
        <th scope="col">View Detail</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr style="color: #000066;">
            <td>@item.Booking_Date</td>
            <td>@item.Show_Date</td>
            <td>@item.Show_Time</td>
            <td style="width: 150px;">@item.Movie_Name</td>
            <td style="width: 50px;">@item.Ticket_No</td>
            <td>
                <a href='javascript:mypopup("@Url.Action("BookingDetail", "UserProfile", new { id = @item.Ticket_Id })","400","450");' style="color: #0000CC; text-decoration: underline;">View</a>
            </td>
        </tr>
    }
</table>

cinema/Views/Shared/_MovieSlidShow.cshtml
@model List<String>
@foreach (String item in Model)
{
    <li><a href="@Url.Content("~/" + item)" title=""></a></li>
}

cinema/Views/Shared/_SelectShow.cshtml
@{ 
}
<form action="@Url.Action("MakeShowSelection", "Public")" method="post" onsubmit="return fn_ValidateForm();">
    <div align="center" style="width: 250px">
        <br />
        <table class="style1">
            <tr>
                <td align="left">Select a Movie --</td>
            </tr>
            <tr>
                <td align="left">
                    @Html.DropDownList("ddlShowMovie", (List<SelectListItem>)(ViewBag.RunningMovies), new { id = "ddlShowMovie", onchange = "fn_OnMovieChange();" })
                </td>
            </tr>
            <tr>
                <td align="left">Select a ShowDate --</td>
            </tr>
            <tr>
                <td align="left">
                    @Html.DropDownList("ddlShowDate", new List<SelectListItem>() { new SelectListItem() { Text = "--SELECT--", Value = "0" } }, new { id = "ddlShowDate", onchange = "fn_OnDateChange();" })
                </td>
            </tr>
            <tr>
                <td align="left">Select a ShowTime --</td>
            </tr>
            <tr>
                <td align="left">
                    @Html.DropDownList("ddlShowTime", new List<SelectListItem>() { new SelectListItem() { Text = "--SELECT--", Value = "0" } }, new { id = "ddlShowTime"})
                </td>
            </tr>
        </table>
        <br />
        <div style="float: right">
            <input type="image" src="@Url.Content("~/images/appImages/go.png")" id="btnGo" title="GO" alt=""  style=" width:40px; height:40px;" />
        </div>
    </div>
</form>
<script type="text/javascript">

    function fn_ValidateForm() {
        if ($("#ddlShowMovie").val() == "0") {
            alert("Please select a movie.");
            return false;
        }
        if ($("#ddlShowDate").val() == "0") {
            alert("Please select a date.");
            return false;
        }
        if ($("#ddlShowTime").val() == "0") {
            alert("Please select a time.");
            return false;
        }

        return true;
    }

    function fn_OnMovieChange() {
        $("#ddlShowDate").empty();
        $("#ddlShowDate").html("<option value='0'>Loading...</option>");
        $.ajax({
            url: "@Url.Action("FillDateList", "Service")",
            data: "{'pMovieTitle':'" + $("#ddlShowMovie").val() + "'}",
            type: "POST",
            dataType: "json",
            contentType: "application/json",
            success: function (response) {
                $("#ddlShowDate").empty();
                $.each(response, function (i, obj) {
                    $("#ddlShowDate").append("<option value='" + obj.value + "'>" + obj.text + "</option>");
                });
            },
            error: function () { alert("Error in application."); }
        });
    }

    function fn_OnDateChange() {
        $("#ddlShowTime").empty();
        $("#ddlShowTime").html("<option value='0'>Loading...</option>");
        $.ajax({
            url: "@Url.Action("FillTimeList", "Service")",
            data: "{'pMovieTitle':'" + $("#ddlShowMovie").val() + "','pMovieDate':'" + $("#ddlShowDate").val() + "'}",
            type: "POST",
            dataType: "json",
            contentType: "application/json",
            success: function (response) {
                $("#ddlShowTime").empty();
                $.each(response, function (i, obj) {
                    $("#ddlShowTime").append("<option value='" + obj.value + "'>" + obj.text + "</option>");
                });
            },
            error: function () { alert("Error in application."); }
        });
    }

</script>